version: '3.8'

services:
  transcriptor:
    build:
      context: .
    image: transcriptor-whisper-img
    container_name: transcriptor-whisper
    ports:
      - "8010:8010"
    dns:
      - "8.8.8.8"
      - "8.8.4.4"
    #volumes:
    #  - ./app:/app/app
    #restart: unless-stopped
